"""empty message

Revision ID: ac3b17282925
Revises: 06c3e3242926
Create Date: 2021-05-13 23:47:22.974855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac3b17282925'
down_revision = '06c3e3242926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('sex', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sex')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
